# Generated by Django 3.0.6 on 2020-05-15 01:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=30)),
                ('game', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
