let Colors = []
Colors["blank"] = "gray"
Colors["active"] = "blue"
Colors["pipe_U_large"] = "linear-gradient(to right, gray 5%,red 5%,red 95%, gray 95%)"
Colors["pipe_D_large"] = "linear-gradient(to right, gray 5%,red 5%, red 95%, gray 95%)"
Colors["pipe_L_large"] = "linear-gradient(to bottom, gray 5%,red 5%, red 95%, gray 95%)"
Colors["pipe_R_large"] = "linear-gradient(to bottom, gray 5%,red 5%, red 95%, gray 95%)"
Colors["pipe_U_medium"] = "linear-gradient(to right, gray 20%,red 20%, red 80%, gray 80%)"
Colors["pipe_D_medium"] = "linear-gradient(to right, gray 20%,red 20%, red 80%, gray 80%)"
Colors["pipe_L_medium"] = "linear-gradient(to bottom, gray 20%,red 20%, red 80%, gray 80%)"
Colors["pipe_R_medium"] = "linear-gradient(to bottom, gray 20%,red 20%, red 80%, gray 80%)"
Colors["pipe_U_small"] = "linear-gradient(to right, gray 33%,red 33%, red 67%, gray 67%)"
Colors["pipe_D_small"] = "linear-gradient(to right, gray 33%,red 33%, red 67%, gray 67%)"
Colors["pipe_L_small"] = "linear-gradient(to bottom, gray 33%,red 33%, red 67%, gray 67%)"
Colors["pipe_R_small"] = "linear-gradient(to bottom, gray 33%,red 33%, red 67%, gray 67%)"
Colors["split"] = "black"
Colors["wall"] = "#51121B"
Colors["tap"] = "green"
Colors["tap_active"] = "yellow"
export default Colors;

//"linear-gradient(to right, white 20%,red 21%, white 81%)"