# Generated by Django 3.0.6 on 2020-05-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0002_auto_20200515_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='user',
            new_name='game_id',
        ),
    ]
