# Generated by Django 3.0.6 on 2020-05-20 09:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0003_auto_20200518_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pressure',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
