# Generated by Django 3.0.6 on 2020-05-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0006_game_initial_pressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
