# Generated by Django 3.0.6 on 2020-05-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0007_game_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='budget',
            field=models.IntegerField(default=0),
        ),
    ]
