# Generated by Django 3.0.6 on 2020-07-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0009_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
