# Generated by Django 3.0.6 on 2020-07-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0010_game_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='height',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='game',
            name='width',
            field=models.IntegerField(default=22),
        ),
    ]
