# Generated by Django 3.0.6 on 2020-08-23 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0012_auto_20200818_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Game')),
            ],
        ),
    ]
